# Generated by Django 3.2.7 on 2021-11-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Название статьи',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Текст статьи',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Автор комментария',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Комментарий',
        ),
        migrations.AddField(
            model_name='article',
            name='article_text',
            field=models.TextField(default=None, verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_title',
            field=models.CharField(default=None, max_length=256, verbose_name='Название статьи'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default=None, max_length=256, verbose_name='Автор комментария'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default=None, verbose_name='Комментарий'),
        ),
    ]
